[symbols]
# Additional symbol refs
ref = [
    "sigaction",
    "pthread_attr_setscope",
    "pthread_attr_setschedpolicy",
    "pthread_attr_getschedpolicy",
    "pthread_attr_getschedparam",
    "pthread_join",
    "pthread_setschedparam",
    "pthread_attr_setschedparam",
    "pthread_detach",
    "pthread_equal",
    "pthread_key_delete",
    "pthread_setname_np",
    "pthread_mutexattr_settype",
    "pthread_mutexattr_setprotocol",
    "pthread_mutex_trylock",
    "pthread_mutexattr_getprotocol",
    "clock_getres",
    "pathconf",
    "truncate",
    "utime",
    "__dso_handle",
    "unlinkat",
    "_GLOBAL_OFFSET_TABLE_",
    "rtems_message_queue_receive",
    "pipe",
    "mq_timedsend",
    "mq_send",
    "mq_receive",
    "mq_close",
    "mq_timedreceive",
    "mq_open",
    "mq_unlink",
    "mq_getattr",
    "getrusage",
    "rtems_libio_count_open_iops",
    "getppid",
    "__ctype_ptr__",

    # Cexpsh stuff
    "cexpModuleName",
    "cexpModuleInfo",
    "cexpModuleUnload",
]

# Regex searches in existing symbols/libs
ref_regex = [
    "_+ctype.*",
]

# These symbols cause problems during linking
exclude = [
    "towctrans_l",
    "towctrans",
    "_towctrans_r",
    "_Stack_Allocator_allocate_for_idle_static",
]

# These files cause issues on i386
[symbols.i386]
exclude_files = [
    "libm_a-catanhl.o",
    "libm_a-s_scalbnl.o",
    "libm_a-f_lrintl.o",
    "libm_a-f_rintl.o",
    "libm_a-f_llrintl.o",
    "libm_a-s_logl.o",
    "libm_a-casinl.o",
    "libm_a-s_expl.o",
    "libm_a-cacoshl.o",
    "libm_a-e_powl.o",
    "libm_a-csinhl.o",
    "libm_a-cacosl.o",
    "libm_a-log10l.o",
    "libm_a-ccosl.o",
    "libm_a-b_tgammal.o",
    "libm_a-s_fmal.o",
    "libm_a-ldexpl.o",
    "libm_a-scalblnl.o",
    "libm_a-casinhl.o",
    "libm_a-s_asinhl.o",
    "libm_a-e_atanhl.o",
    "libm_a-e_acoshl.o"
]
